.TH XOWL 1 "" 
.SH NAME
.PP
xowl - X11 Obstinate Window Lister
.SH SYNOPSIS
.PP
\f[B]xowl\f[]
.SH DESCRIPTION
.PP
A popup window switcher/launcher.
.PP
License: MIT/X11
.SH USAGE
.PP
See config.h for customization.
.SH SEE ALSO
.PP
\f[B]xoat\f[] (1)
.SH AUTHOR
.PP
Sean Pringle <sean.pringle@gmail.com>
